### ISSUE TITLE
Consider releasing 1.0.0-beta.1 as 0.11 

### ISSUE THREAD

**Issue by ontofractal** [teamon/tesla#206] opened 2018-06-06 10:08 UTC
@teamon, do you think it's possible for you to release 1.0.0 beta branch as 0.11? It is not possible to publish hex.pm packages using 1.0.0-beta.1 on hex.pm without adding a -rc or -beta suffix to the package version. 

The hex.pm error in question is "** (Mix) A stable package release cannot have a pre-release dependency".

Thanks

**Comment by ericmj** [comment] 2018-06-06 11:37
If you want to depend on unstable packages you need to publish your package as unstable as well. I don't think the solution is to release a stable version from code that the maintainers think is unstable.

The reason for the error from Hex is not to push maintainers to publish code as stable that they really think is unstable – it is to push consumers of the package to also mark their code as unstable.

**Comment by ontofractal** [comment] 2018-06-06 11:53
@ericmj Thanks for the reply, I may have been somewhat unclear.

I don't want a stable package to depend on a unstable one. My point is that I'm unable to publish 0.1.0 (already marked unstable by semver convention) on hex.pm with 1.0.0-beta.1 Tesla dependency. It seems that the only way to publish a package on hex.pm is to use `0.1.0-{beta/rc}.n` version which is a bit confusing and redundant.

Btw, I fully agree with you that packages with versions >= 1.0.0 should not have unstable packages as a dependency without the unstable version designation.

**Comment by ericmj** [comment] 2018-06-06 11:56
The problem is the prevalent use of <= 1.0.0 versions so they requirements must exist for all otherwise it doesn’t do much. I think you should publish your package as 0.1.0-whatever (why is that confusing?) or use Tesla 0.10 for now.

**Comment by ontofractal** [comment] 2018-06-06 12:18
Using Tesla 0.10 will require a rewrite in the future which is quite undesirable :sweat_smile: 

From my point of view, `0.1.0-beta/alpha/rc.0` indicates that the package is in very early stages of development and I should wait at least until 0.1.0 before using the dependency. Hence the confusion.   

Also if I publish a package as `0.1.0-rc.0` and then add a significant amount of new features do I publish the next version as 0.1.0-rc.1 or 0.2.0-rc.0?

**Comment by ericmj** [comment] 2018-06-06 13:53
I would say `0.1.0` indicates it's in early development and `-beta` indicates it's unstable. If you add a bunch of new features I think you should bump the minor version.

**Comment by teamon** [comment] 2018-06-07 09:55
Nah, I'll just release [v1.0.0](https://github.com/teamon/tesla/releases/tag/v1.0.0) 🎁 

(I'm closing this issue but feel free to continue discussion here if needed)

**Closed by teamon** 2018-06-07 09:55 UTC
