### ISSUE TITLE
Feature Request: Allow a function for Tesla.Middleware.BaseUrl

### ISSUE THREAD

**Issue by halostatue** [teamon/tesla#444] opened 2021-01-29 19:49 UTC
This would allow for dynamic resolution of the base URL:

```elixir
middleware = [
  {Tesla.Middleware.BaseUrl, fn _ -> System.get_env("MY_API_BASE_URL") end}
]
```

The expectation would be that the function would be a `/1` function receiving `env`. Alternatively, it could be implemented to accept either a `/0` or a `/1` (not a bad choice, either).

**Comment by teamon** [comment] 2021-01-29 19:59
Duplicate of https://github.com/teamon/tesla/pull/405

**Closed by teamon** 2021-01-29 19:59 UTC

**Comment by halostatue** [comment] 2021-01-29 20:16
Yes, this is a duplicate of #405, but I have a case where I _cannot_ merely make this a runtime configuration. I have a case where I need runtime configuration of runtime configuration. In specific:

1. Making a request to resource A requires an authentication token.
2. If I do not have an authentication token, or the token has expired, I need to request a new token. I have middleware that will obtain an active or new authentication token from a GenServer and insert that as an Authorization header.
3. The API that returns a new authentication token _also_ returns the base URL I need to call for requesting resource A.
4. I need to set my Base URL based on the authentication token.

Even if #445 isn’t implemented, being able to add a function would allow me to do this as:

```elixir
middleware = [
  …,
  {Tesla.Middleware.BaseUrl, fn -> TokenStore.get_token(credentials).extra["rest_url"] end)}
]
```

I should not be calling `TokenStore.get_token/1` during the construction of the client, but only when the API call is actually made.
